### ISSUE TITLE
Potion Ability can only be gotten one time per world if "cleared" command is used. 

### ISSUE THREAD

**Issue by MLMII** [ToCraft/potionabilities#1]
When you get a random potion effect and use the "clear" command to remove the ability if it's one you don't want you can't obtain a different one.  

I'd recommend adding a command to give a player an ability.

Thank you for your time.

ycdm-1.0.2-fabric    1.20.1 version

**Comment by ToCraft** [comment]
You can use `/ycdm structures clear`
To use the same structure again.
Nevertheless, I'll try to add a `/ycdm potion set`-command in the next update

**Comment by MLMII** [comment]
Ah, I didn't realize that each temple could only be used once ... thanks.
